services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    extends:
      file: compose.common.yaml
      service: common
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 6881:6881
    volumes:
      - ${APP_PATH}/qbittorrent:/config/qBittorrent
      - ${DATA_PATH}/torrents:/downloads
