services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    extends:
      file: compose.common.yaml
      service: common
    environment:
      - UMASK_SET=002
      - webUIPort=8265
      - serverPort=8266
      - internalNode=true
      - inContainer=true
      - auth=true
      - ffmpegVersion=6
      - nodeName=Tdarr node
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - a
    volumes:
      - ${APP_PATH}/tdarr/server:/app/server
      - ${APP_PATH}/tdarr/configs:/app/configs
      - ${APP_PATH}/tdarr/logs:/app/logs
      - ${DATA_PATH}/data:/data
      - ${DATA_PATH}/transcode_cache:/temp
    links:
      - sonarr
      - radarr
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
