services:
  common:
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
        loki-retries: 2
        loki-batch-size: 400
        max-size: 10m
        max-file: 2
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - TZ=${TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"
