services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    user: root
    volumes:
      - ../configs/loki.yaml:/etc/loki/loki.yaml
      - ${APP_PATH}/loki:/data
    command: -config.file=/etc/loki/loki.yaml
    extends:
      file: ./compose.common.yaml
      service: common
  alloy:
    container_name: alloy
    image: grafana/alloy:latest
    privileged: true
    cap_add:
      - SYS_TIME
    extends:
      file: compose.common.yaml
      service: common
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /run/udev/data:/run/udev/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../configs/config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    pid: host
    links:
      - prometheus
      - loki
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    extends:
      file: compose.common.yaml
      service: common
    volumes:
      - ../configs/prometheus.yaml:/prometheus/prometheus.yml
    command:
      - --web.enable-remote-write-receiver
  grafana:
    container_name: grafana
    image: grafana/grafana
    extends:
      file: compose.common.yaml
      service: common
    volumes:
      - ../grafana/:/etc/grafana/provisioning/
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Authelia
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GRAFANA_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GRAFANA_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES="openid profile email"
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.${DOMAIN}/api/authz/forward-auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.${DOMAIN}/api/authz/forward-auth/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.${DOMAIN}/api/authz/forward-auth/userinfo
      - GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH=preferred_username
      - GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH=groups
      - GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH=name
      - GF_AUTH_GENERIC_OAUTH_USE_PKCE=true
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    links:
      - prometheus
      - loki
