services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    extends:
      file: compose.common.yaml
      service: common
    volumes:
      - ${APP_PATH}/sonarr:/config
      - ${DATA_PATH}:/data
    links:
      - autoscan
      - prowlarr
      - qbittorrent
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    extends:
      file: compose.common.yaml
      service: common
    volumes:
      - ${APP_PATH}/radarr:/config
      - ${DATA_PATH}:/data
    links:
      - autoscan
      - prowlarr
      - qbittorrent
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    extends:
      file: compose.common.yaml
      service: common
    links:
      - flaresolverr
    volumes:
      - ${APP_PATH}/prowlarr:/config
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    extends:
      file: compose.common.yaml
      service: common
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    extends:
      file: compose.common.yaml
      service: common
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 6881:6881
    volumes:
      - ${APP_PATH}/qbittorrent:/config/qBittorrent
      - ${DATA_PATH}/torrents:/downloads
