services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    extends:
      file: compose.common.yaml
      service: common
    volumes:
      - ${APP_PATH}/sonarr:/config
      - ${DATA_PATH}:/data
    links:
      - autolanguageconfig
      - autoscan
      - prowlarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    extends:
      file: compose.common.yaml
      service: common
    volumes:
      - ${APP_PATH}/radarr:/config
      - ${DATA_PATH}:/data
    links:
      - autolanguageconfig
      - autoscan
      - prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    extends:
      file: compose.common.yaml
      service: common
    links:
      - flaresolverr
    volumes:
      - ${APP_PATH}/prowlarr:/config
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    extends:
      file: compose.common.yaml
      service: common
    links:
      - sonarr
      - radarr
    volumes:
      - ${APP_PATH}/config:/config
      - ${DATA_PATH}:/data
    restart: unless-stopped
