services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: unless-stopped
    volumes:
      - ../configs/loki.yml:/etc/loki/config.yaml
  grafana:
    image: grafana/grafana
    container_name: grafana
    extends:
      file: compose.common.yaml
      service: common
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Authelia
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GRAFANA_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GRAFANA_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.${DOMAIN}/api/authz/forward-auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.${DOMAIN}/api/authz/forward-auth/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.${DOMAIN}/api/authz/forward-auth/userinfo
      - GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH=preferred_username
      - GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH=groups
      - GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH=name
      - GF_AUTH_GENERIC_OAUTH_USE_PKCE=true
