- Apps:
    - Plex:
        icon: plex.svg
        href: "https://plex.{{HOMEPAGE_VAR_DOMAIN}}"
        container: plex
        server: docker
        widget:
          type: plex
          url: "{{HOMEPAGE_VAR_PLEX_URL}}"
          key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"
    - Jellyseerr:
        icon: jellyseerr.svg
        href: "https://{{HOMEPAGE_VAR_DOMAIN}}"
        container: jellyseerr
        server: docker

    - Sonnar:
        icon: sonarr.svg
        href: "https://sonarr.{{HOMEPAGE_VAR_DOMAIN}}"
        container: sonarr
        server: docker
        widget:
          type: sonarr
          url: "{{HOMEPAGE_VAR_SONARR_API_URL}}"
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
          queued: false
          series: false
    - Radarr:
        icon: radarr.svg
        href: "https://radarr.{{HOMEPAGE_VAR_DOMAIN}}"
        container: radarr
        server: docker
        widget:
          type: radarr
          url: "{{HOMEPAGE_VAR_RADARR_API_URL}}"
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
          queued: false
          movies: false
    - Prowlarr:
        icon: prowlarr.svg
        href: "https://prowlarr.{{HOMEPAGE_VAR_DOMAIN}}"
        container: prowlarr
        server: docker
        widget:
          type: prowlarr
          url: "{{HOMEPAGE_VAR_PROWLARR_API_URL}}"
          key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
          numberOfQueries: false
          numberOfGrabs: false
    - Bazarr:
        icon: bazarr.svg
        href: "https://bazarr.{{HOMEPAGE_VAR_DOMAIN}}"
        container: bazarr
        server: docker
        widget:
          type: bazarr
          url: "{{HOMEPAGE_VAR_BAZARR_API_URL}}"
          key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"

    - Dozzle:
        icon: dozzle.svg
        href: "https://logs.{{HOMEPAGE_VAR_DOMAIN}}"
        container: dozzle
        server: docker
    - Qbittorrent:
        icon: qbittorrent.svg
        href: "https://qbittorrent.{{HOMEPAGE_VAR_DOMAIN}}"
        container: qbittorrent
        server: docker
        widget:
          type: qbittorrent
          url: "{{HOMEPAGE_VAR_QBITTORRENT_API_URL}}"
