title: Antoine'Dashboard
theme: dark
useEqualHeights: true
headerStyle: clean
statusStyle: "dot"
layout:
  Utilities:
    header: false
    style: row
    columns: 2
  Apps:
    header: false
    style: row
    columns: 2
