---
# Homepage configuration
# See https://fontawesome.com/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Dashboard"
subtitle: "Antoine Bouteiller"

header: true
footer: false

columns: "auto"
connectivityCheck: true

proxy:
  useCredentials: true

stylesheet:
  - "assets/themes/catpuccin-mocha.css"
  - "assets/themes/catpuccin-latte.css"

logo: assets/images/dark_circle.png
links:
  - name: "Trash guide SQP"
    icon: "fas fa-trash"
    url: "https://trash-guides.info/SQP/"
    target: "_blank" # optional html tag target attribute
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/AntoBouteiller"
    target: "_blank" # optional html tag target attribute
  - name: "The Poster DB"
    icon: "fas fa-database"
    url: "https://theposterdb.com/"
    target: "_blank" # optional html tag target attribute
  - name: "Piracy Megathread"
    icon: "fab fa-reddit"
    url: "https://www.reddit.com/r/Piracy/wiki/megathread/"
    target: "_blank" # optional html tag target attribute

services:
  - name: "Serveur"
    icon: "fas fa-server"
    items:
      - name: "Sonarr"
        type: "Sonarr"
        apikey: c95034dea8e54e349b025bd34bd8f853
        logo: assets/logos/sonarr.svg
        url: https://sonarr.antoinebouteiller.duckdns.org
        target: "_blank"
      - name: "Radarr"
        type: "Radarr"
        apikey: 2b89e613730e4685b838498435a7486d
        logo: assets/logos/radarr.svg
        url: https://radarr.antoinebouteiller.duckdns.org
        target: "_blank"
      - name: "Prowlarr"
        type: "Prowlarr"
        apikey: 60f8b32a7c6d471d9837701d20e3ac42
        logo: assets/logos/prowlarr.svg
        url: https://prowlarr.antoinebouteiller.duckdns.org
        target: "_blank"
      - name: "qBittorrent"
        type: "qBittorrent"
        logo: assets/logos/qbittorrent.svg
        url: https://qbittorrent.antoinebouteiller.duckdns.org
        target: "_blank"
      - name: "DuckDns"
        logo: assets/logos/duckdns.png
        url: https://www.duckdns.org
        target: "_blank"
      - name: "Bazarr"
        logo: assets/logos/bazarr.svg
        url: https://bazarr.antoinebouteiller.duckdns.org
        target: "_blank"
  - name: "Applications"
    icon: "fas fa-microchip"
    items:
      - name: "Plex"
        logo: assets/logos/plex.svg
        url: https://plex.antoinebouteiller.duckdns.org
        target: "_blank"
      - name: "Overseerr"
        logo: assets/logos/overseerr.svg
        url: https://antoinebouteiller.duckdns.org
        target: "_blank"
  - name: "Monitoring"
    icon: "fas fa-microchip"
    items:
      - name: "Trakt"
        logo: assets/logos/trakt.svg
        url: https://trakt.tv
        target: "_blank"
      - name: "Tautulli"
        type: "Tautulli"
        apikey: 2c4bf6057dbf4a18869c950a286fd260
        logo: assets/logos/tautulli.svg
        url: https://tautulli.antoinebouteiller.duckdns.org
        target: "_blank"
      - name: "Fan Controller"
        logo: assets/logos/coolercontrol.svg
        url: https://fancontroller.antoinebouteiller.duckdns.org
        target: "_blank"
      - name: "Grafana"
        logo: assets/logos/grafana.svg
        url: https://grafana.antoinebouteiller.duckdns.org
        target: "_blank"
